### PR TITLE
Feat/cc 144 hero and why us

### PR DESCRIPTION
**Pull request by Cecilia0109**
1、Add Hero and Why choose us page
2、 the basketball picture can move when user hover it.
3、the content of 'Why Choos Us' page will be changed when BA give the new content.
4、add card animation in Why Choos Us' page
Screen Shot 2022-11-25 at 12 05 29 am
Screen Shot 2022-11-25 at 12 06 11 am
Screen Shot 2022-11-25 at 12 06 46 am
Screen Shot 2022-11-25 at 12 07 27 am

### CODE REVIEW

**Comment by tatoMa** [comment]
The text section is still covered 3d module on the desktop view. Maybe try to use an absolute layer with no background of the text section and put it on top of the hero section.

image

**Comment by tatoMa** [comment]
The animation of the why us section is acting weird with unstable moving transitions also should be invisible outside of the outer section. Take a look at the template section as an example.

**Comment by Cecilia0109** [comment]
> The animation of the why us section is acting weird with unstable moving transitions also should be invisible outside of the outer section. Take a look at the template section as an example.
Fixed

**Review by tatoMa — APPROVED** [review]
LGTM

**Review by guanlinau — APPROVED** [review]
LGTM

**Pull request merged**
